lannguage: ruby
rvm:
  - 2.0.0
  - 2.1.0
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake refinery:testing:dummy_app > /dev/null"
script:
  - "DISPLAY=:99.0 bundle exec rspec spec"
